"""
Enterprise PDF Rendering Service using WeasyPrint.
Converts AI-generated Markdown into pixel-perfect, print-ready PDFs
with native pagination, headers, footers, and a cover page.
"""
import io
import asyncio
import markdown2
from datetime import datetime


# ── Professional PDF CSS ─────────────────────────────────────────────────────
PDF_CSS_STRING = """
@import url('https://fonts.googleapis.com/css2?family=Plus+Jakarta+Sans:wght@300;400;500;600;700&display=swap');

@page {
    size: A4;
    margin: 2.5cm 2cm 3cm 2cm;
    
    @top-right {
        content: "CONFIDENTIAL";
        font-family: 'Plus Jakarta Sans', system-ui, sans-serif;
        font-size: 8pt;
        color: #a1a1aa;
        letter-spacing: 0.15em;
    }
    
    @bottom-center {
        content: counter(page) " / " counter(pages);
        font-family: 'Plus Jakarta Sans', system-ui, sans-serif;
        font-size: 8pt;
        color: #71717a;
    }
    
    @bottom-right {
        content: "Generated by BidForge";
        font-family: 'Plus Jakarta Sans', system-ui, sans-serif;
        font-size: 7pt;
        color: #a1a1aa;
    }
}

@page :first {
    @top-right { content: none; }
    @bottom-center { content: none; }
    @bottom-right { content: none; }
}

* { box-sizing: border-box; }

body {
    font-family: 'Plus Jakarta Sans', system-ui, -apple-system, sans-serif;
    color: #111827;
    background-color: #ffffff;
    line-height: 1.7;
    font-size: 10.5pt;
}

/* ── Cover Page ─────────────────────────────────── */
.cover-page {
    page-break-after: always;
    display: flex;
    flex-direction: column;
    justify-content: center;
    min-height: 85vh;
    text-align: center;
    padding: 4cm 2cm;
}

.cover-page h1 {
    font-size: 28pt;
    font-weight: 700;
    color: #09090b;
    margin-bottom: 0.3em;
    border: none;
    padding: 0;
    letter-spacing: -0.02em;
}

.cover-page .subtitle {
    font-size: 14pt;
    color: #52525b;
    font-weight: 400;
    margin-bottom: 3em;
}

.cover-page .meta {
    font-size: 10pt;
    color: #71717a;
    line-height: 2;
}

.cover-page .meta strong {
    color: #27272a;
    font-weight: 600;
}

.cover-page .divider {
    width: 80px;
    height: 3px;
    background: linear-gradient(90deg, #3b82f6, #8b5cf6);
    margin: 2em auto;
    border-radius: 2px;
}

/* ── Typography ─────────────────────────────────── */
h1, h2, h3, h4 {
    color: #09090b;
    font-weight: 700;
    page-break-after: avoid;
}

h1 {
    font-size: 20pt;
    border-bottom: 2px solid #e4e4e7;
    padding-bottom: 8px;
    margin-top: 1.8em;
    margin-bottom: 0.8em;
}

h2 {
    font-size: 15pt;
    border-bottom: 1px solid #f4f4f5;
    padding-bottom: 5px;
    margin-top: 1.5em;
    margin-bottom: 0.6em;
}

h3 {
    font-size: 12pt;
    margin-top: 1.2em;
    margin-bottom: 0.5em;
    color: #27272a;
}

p {
    margin-bottom: 1em;
    color: #3f3f46;
    orphans: 3;
    widows: 3;
}

strong, b { color: #09090b; font-weight: 600; }

/* ── Lists ──────────────────────────────────────── */
ul, ol {
    margin-bottom: 1.2em;
    padding-left: 1.5em;
}

li {
    margin-bottom: 0.4em;
    color: #3f3f46;
}

/* ── Tables ─────────────────────────────────────── */
table {
    width: 100%;
    border-collapse: collapse;
    margin: 1.5em 0;
    font-size: 9.5pt;
    page-break-inside: avoid;
}

th, td {
    padding: 10px 14px;
    border: 1px solid #e4e4e7;
    text-align: left;
    vertical-align: top;
}

th {
    background-color: #f4f4f5;
    font-weight: 600;
    color: #09090b;
    text-transform: uppercase;
    font-size: 8pt;
    letter-spacing: 0.05em;
}

tr:nth-child(even) td {
    background-color: #fafafa;
}

/* ── Blockquotes (Win Score, Alerts) ────────────── */
blockquote {
    border-left: 4px solid #3b82f6;
    background-color: #eff6ff;
    padding: 14px 18px;
    margin: 1.5em 0;
    border-radius: 0 6px 6px 0;
    color: #1e3a8a;
    page-break-inside: avoid;
}

blockquote p { color: #1e3a8a; }
blockquote strong { color: #1e40af; }

/* ── Code blocks (for Mermaid placeholders) ─────── */
pre, code {
    font-family: 'JetBrains Mono', monospace;
    font-size: 9pt;
    background-color: #f4f4f5;
    border-radius: 4px;
    padding: 2px 6px;
}

pre {
    padding: 1em;
    overflow-x: auto;
    border: 1px solid #e4e4e7;
    margin: 1em 0;
    page-break-inside: avoid;
}

/* ── Horizontal Rules ───────────────────────────── */
hr {
    border: none;
    border-top: 1px solid #e4e4e7;
    margin: 2em 0;
}

/* ── Links ──────────────────────────────────────── */
a { color: #2563eb; text-decoration: none; }
"""


def _build_cover_page(client_name: str, rfp_title: str, org_name: str, proposal_date: str = "") -> str:
    """Generate a professional cover page HTML block."""
    date_str = proposal_date or datetime.now().strftime("%B %d, %Y")
    return f"""
    <div class="cover-page">
        <h1>{rfp_title}</h1>
        <div class="subtitle">Prepared exclusively for {client_name}</div>
        <div class="divider"></div>
        <div class="meta">
            <strong>Submitted by:</strong> {org_name}<br>
            <strong>Date:</strong> {date_str}<br>
            <strong>Classification:</strong> Confidential
        </div>
    </div>
    """


async def render_proposal_pdf(
    markdown_content: str,
    client_name: str = "Client",
    rfp_title: str = "Proposal",
    org_name: str = "BidForge",
    proposal_date: str = "",
) -> bytes:
    """
    Convert Markdown proposal content into a professional PDF using WeasyPrint.
    Returns raw PDF bytes.
    """
    # Convert Markdown → HTML
    html_body = markdown2.markdown(
        markdown_content,
        extras=[
            "tables",
            "fenced-code-blocks",
            "break-on-newline",
            "cuddled-lists",
            "header-ids",
            "strike",
            "task_list",
        ]
    )

    # Build the full HTML document with cover page
    cover_html = _build_cover_page(client_name, rfp_title, org_name, proposal_date)
    
    full_html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{rfp_title} — {org_name}</title>
</head>
<body>
    {cover_html}
    {html_body}
</body>
</html>"""

    # Render PDF in a thread to avoid blocking asyncio event loop
    def _render():
        from weasyprint import HTML, CSS
        pdf_css = CSS(string=PDF_CSS_STRING)
        html_doc = HTML(string=full_html)
        return html_doc.write_pdf(stylesheets=[pdf_css])

    pdf_bytes = await asyncio.to_thread(_render)
    return pdf_bytes
